services:
    postgres:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        restart: always
        env_file: .env
        #volumes:
            #- pgdata:/var/lib/postgresql/data
            #- ./postgres/init:/docker-entrypoint-initdb.d
            #- dbbackup:/dbbackup
    adminer:
        image: adminer
        #restart: always
        ports:
            - "8183:8080"
    tomcat_app:
        container_name: tomcat
        image: tomcat:9.0
        restart: always
        #volumes:
        #    - ./sample.war:/usr/local/tomcat/webapps/sample.war:ro
    #proxy:
    #    container_name: nginx
    #    image: nginx
    #    ports:
    #        - 80:80
    #    volumes:
    #        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        #restart: always
        ports:
            - "8082:8082"