CREATE OR REPLACE VIEW ELIST_PROD_ACTIVE_INGRED_MV
AS 
SELECT 
      NULL      AS PRODUCTID,
      NULL      AS DOCUMENTID,
      NULL      AS SUBSTANCEUNII,
      NULL      AS SUBSTANCENAME,
      NULL      AS STRENGTHNUMBER,
      NULL      AS STRENGTHNUMERATORUNIT,
      NULL      AS STRENGTHDENOMINATORUNIT,
      NULL      AS BASISOFSTRENGTH,
      NULL      AS REFERENCEDRUGUNII,
      NULL      AS REFERENCEDRUGNAME,
      NULL      AS ACTIVEMOIETY_1_UNII,
      NULL      AS ACTIVEMOIETY_1_NAME,
      NULL      AS ACTIVEMOIETY_2_UNII,
      NULL      AS ACTIVEMOIETY_2_NAME,
      NULL      AS ORIGINALNUMERATORNUMBER,
      NULL      AS ORIGINALNUMERATORUNIT,
      NULL      AS ORIGINALDENOMINATORNUMBER,
      NULL      AS ORIGINALDENOMINATORUNIT
      from dual;
