CREATE OR REPLACE VIEW ELIST_PRODUCT_MV
AS 
SELECT 
      NULL      AS PRODUCTID,
      NULL      AS PRODUCTNDC,
      NULL      AS PRODUCTTYPECODE,
      NULL      AS PRODUCTTYPENAME,
      NULL      AS PROPRIETARYNAME,
      NULL      AS PROPRIETARYNAMESUFFIX,
      NULL      AS NONPROPRIETARYNAME,
      NULL      AS SOURCEPRODUCTID,
      NULL      AS SOURCEPRODUCTNDC,
      NULL      AS DEASCHEDULE,
      NULL      AS DOSAGEFORMCODE,
      NULL      AS DOSAGEFORMNAME,
      NULL      AS MARKETINGSTATUS,
      NULL      AS STARTMARKETINGDATE,
      NULL      AS ENDMARKETINGDATE,
      NULL      AS MARKETINGCATEGORYCODE,
      NULL      AS MARKETINGCATEGORYNAME,
      NULL      AS APPLICATIONNUMBER,
      NULL      AS LABELERNAME,
      NULL      AS LABELERDUNS,
      NULL      AS LABELERNDC,
      NULL      AS REGISTRANTNAME,
      NULL      AS REGISTRANTDUNS,
      NULL      AS IS_LISTED,
      NULL      AS DOCUMENTID
      from dual;
