
CREATE OR REPLACE VIEW ELIST_ESTABLISHMENT
AS
SELECT
    NULL     AS FEI_NUMBER,
    NULL     AS DUNS_NUMBER,
    NULL     AS NDC_LABELER_CODE,
    NULL     AS FIRM_NAME,
    NULL     AS ADDRESS,
    NULL     AS CITY,
    NULL     AS STATE,
    NULL     AS ZIP,
    NULL     AS COUNTRY,
    NULL     AS COUNTRY_CODE,
    NULL     AS ESTABLISHMENT_ID
    from dual;
