DROP MATERIALIZED VIEW SRSCID_PRODUCT_ALL_TWO_MV;

CREATE MATERIALIZED VIEW SRSCID_PRODUCT_ALL_TWO_MV 
    (PRODUCTID,PRODUCTNDC,NONPROPRIETARYNAME,PRODUCTTYPE,STATUS,
     MARKETINGCATEGORYNAME,ISLISTED,ROUTENAME,APPLICATIONNUMBER,APPTYPE,
     APPNUMBER,COUNTRY,COUNTRYWITHOUTCODE,LABELERNDC,UNITPRESENTATION,
     SOURCE,SOURCE_TYPE,FROMTABLE,PROVENANCE,CREATED_BY,
     CREATE_DATE,MODIFIED_BY,MODIFY_DATE)
TABLESPACE SRSCID
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
NOLOGGING
NOCOMPRESS
BUILD IMMEDIATE
REFRESH FORCE
START WITH SYSDATE
NEXT TRUNC(SYSDATE+1) + 5/24           
WITH PRIMARY KEY
AS
SELECT * FROM SRSCID_PRODUCT_ALL_TWO_V;


CREATE INDEX PRODUCTALLTWOMV_FROMTAB_INDX ON SRSCID_PRODUCT_ALL_TWO_MV
(FROMTABLE)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PRODUCTALLTWOMV_MCN_INDX ON SRSCID_PRODUCT_ALL_TWO_MV
(MARKETINGCATEGORYNAME)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   167
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PRODUCTALLTWOMV_PRODID_INDX ON SRSCID_PRODUCT_ALL_TWO_MV
(PRODUCTID)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PRODUCTALLTWOMV_PROVEN_INDX ON SRSCID_PRODUCT_ALL_TWO_MV
(PROVENANCE)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
           
           
           
