
CREATE OR REPLACE VIEW ELIST_PROD_INACTIVE_INGRED_MV
AS 
SELECT
      NULL      AS PRODUCTID,
      NULL      AS DOCUMENTID,
      NULL      AS SUBSTANCEUNII,
      NULL      AS SUBSTANCENAME,
      NULL      AS STRENGTHNUMBER,
      NULL      AS STRENGTHNUMERATORUNIT,
      NULL      AS STRENGTHDENOMINATORUNIT,
      NULL      AS CONFIDENTIALITYCODE,
      NULL      AS ORIGINALNUMERATORNUMBER,
      NULL      AS ORIGINALNUMERATORUNIT,
      NULL      AS ORIGINALDENOMINATORNUMBER,
      NULL      AS ORIGINALDENOMINATORUNIT
      from dual;
