DROP MATERIALIZED VIEW SRSCID_PRODUCT_ING_ALL_TWO_MV;

CREATE MATERIALIZED VIEW SRSCID_PRODUCT_ING_ALL_TWO_MV 
    (ID,PRODUCTID,BDNUM,SUBSTANCE_KEY,SUBSTANCE_KEY_TYPE,
     BASISOFSTRENGTH,BOS_SUBSTANCE_KEY,BOS_SUBSTANCE_KEY_TYPE,SUBSTANCENAME,SUBSTANCE_APPROVAL_ID,
     SUBSTANCE_UUID,INGREDIENTTYPE,STRENGTHNUMBER,STRENGTHNUMERATORUNIT,ACTIVEMOIETY_1_NAME,
     ACTIVEMOIETY_1_UNII,DOSAGEFORM,FROMTABLE)
TABLESPACE SRSCID
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
NOLOGGING
NOCOMPRESS
BUILD IMMEDIATE
REFRESH FORCE
START WITH SYSDATE
NEXT TRUNC(SYSDATE+1) + 5/24           
WITH PRIMARY KEY
AS 
SELECT * FROM SRSCID_PRODUCT_ING_ALL_TWO_V;


CREATE INDEX SRSCID.PRODUCTINGALLTWOMV_PRODID_INDX ON SRSCID_PRODUCT_ING_ALL_TWO_MV
(PRODUCTID)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX SRSCID.PRODUCTINGALLTWOMV_SUBID_INDX ON SRSCID_PRODUCT_ING_ALL_TWO_MV
(SUBSTANCE_UUID)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX SRSCID.PROD_ING_ALL_2_MV_BDNUM_IDX ON SRSCID_PRODUCT_ING_ALL_TWO_MV
(BDNUM)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX SRSCID.PROD_ING_ALL_2_MV_SKT_IDX ON SRSCID_PRODUCT_ING_ALL_TWO_MV
(SUBSTANCE_KEY_TYPE)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX SRSCID.PROD_ING_ALL_2_MV_SUBSTKEY_IDX ON SRSCID_PRODUCT_ING_ALL_TWO_MV
(SUBSTANCE_KEY)
LOGGING
TABLESPACE SRSCID
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

