
api.base.path: ${API_BASE_PATH:/ginas/app}

gsrs:
  gateway:
    server:
      addHeaders:
        - "Access-Control-Allow-Origin: *"
        - "Access-Control-Allow-Methods: POST, GET, PUT, PATCH, DELETE, OPTIONS"

eureka:
  client:
    registerWithEureka: true 
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761}

spring:
  application:
    name: gateway

debug: true

zuul:
  #this sets sensitiveHeaders to empty list so cookies and auth headers are passed through both ways
  sensitiveHeaders:
  routes:
    ui_beta:
      path: /ginas/app/beta/**
      url: http://localhost:8082
      serviceId: frontend
      stripPrefix: false
    ui_ui:
      path: /ginas/app/ui/**
      url: http://localhost:8082
      serviceId: frontend
      stripPrefix: false

    #############################
    #START adverse-events section
    #############################
    adverseeventpt:
      path: ${api.base.path}/api/v1/adverseeventpt/**
      url: http://localhost:8086/api/v1/adverseeventpt
      serviceId: adverseeventpt
    adverseeventpt_alt:
      path: ${api.base.path}/api/v1/adverseeventpt(**)/**
      url: http://localhost:8086/api/v1/adverseeventpt
      serviceId: adverseeventpt
    adverseeventdme:
      path: ${api.base.path}/api/v1/adverseeventdme/**
      url: http://localhost:8086/api/v1/adverseeventdme
      serviceId: adverseeventdme
    adverseeventdme_alt:
      path: ${api.base.path}/api/v1/adverseeventdme(**)/**
      url: http://localhost:8086/api/v1/adverseeventdme
      serviceId: adverseeventdme
    adverseeventcvm:
      path: ${api.base.path}/api/v1/adverseeventcvm/**
      url: http://localhost:8086/api/v1/adverseeventcvm
      serviceId: adverseeventcvm
    adverseeventcvm_alt:
      path: ${api.base.path}/api/v1/adverseeventcvm(**)/**
      url: http://localhost:8086/api/v1/adverseeventcvm
      serviceId: adverseeventcvm
    #############################
    #END adverse-events section
    #############################

    #############################
    #START applications section
    #############################
    applications_core:
      path: ${api.base.path}/api/v1/applications/**
      url: http://localhost:8083/api/v1/applications
      serviceId: applications_core
    applications_core_alt:
      path: ${api.base.path}/api/v1/applications(**)/**
      url: http://localhost:8083/api/v1/applications
      serviceId: applications_core_alt
    applications_all:
      path: ${api.base.path}/api/v1/applicationsall/**
      url: http://localhost:8083/api/v1/applicationsall
      serviceId: applications_all
    applications_all_alt:
      path: ${api.base.path}/api/v1/applicationsall(**)/**
      url: http://localhost:8083/api/v1/applicationsall
      serviceId: applications_all_alt
    applications_darrts:
      path: ${api.base.path}/api/v1/applicationsdarrts/**
      url: http://localhost:8083/api/v1/applicationsdarrts
      serviceId: applications_darrts
    applications_darrts_alt:
      path: ${api.base.path}/api/v1/applicationsdarrts(**)/**
      url: http://localhost:8083/api/v1/applicationsdarrts
      serviceId: applications_darrts_alt
    applications_searchcount:
      path: ${api.base.path}/api/v1/searchcounts/**
      url: http://localhost:8083/api/v1/searchcounts
      serviceId: applications_searchcount
    applications_searchcount_alt:
      path: ${api.base.path}/api/v1/searchcounts(**)/**
      url: http://localhost:8083/api/v1/searchcounts
      serviceId: applications_searchcount
    #############################
    #END applications section
    #############################

    #############################
    #START clinical-trials section
    #############################
    clinical_trials_us:
      path: ${api.base.path}/api/v1/clinicaltrialsus/**
      url: http://localhost:8089/api/v1/clinicaltrialsus
      serviceId: clinical_trials_us
    clinical_trials_us_alt:
      path: ${api.base.path}/api/v1/clinicaltrialsus(**)/**
      url: http://localhost:8089/api/v1/clinicaltrialsus
      serviceId: clinical_trials_us
    clinical_trials_europe:
      path: ${api.base.path}/api/v1/clinicaltrialseurope/**
      url: http://localhost:8089/api/v1/clinicaltrialseurope
      serviceId: clinical_trials_europe
    clinical_trials_europe_alt:
      path: ${api.base.path}/api/v1/clinicaltrialseurope(**)/**
      url: http://localhost:8089/api/v1/clinicaltrialseurope
      serviceId: clinical_trials_europe  
    #############################
    #END clinical-trials section
    #############################

    #############################
    #START impurities section
    #############################
    impurities_core:
      path: ${api.base.path}/api/v1/impurities/**
      url: http://localhost:8085/api/v1/impurities
      serviceId: impurities_core
    impurities_core_alt:
      path: ${api.base.path}/api/v1/impurities(**)/**
      url: http://localhost:8085/api/v1/impurities
      serviceId: impurities_core
    #############################
    #END impurities section
    #############################

    #############################
    #START invitro-pharmacology  section
    #############################
    invitropharmacology_core:
      path: ${api.base.path}/api/v1/invitropharmacology/**
      url: http://localhost:8090/api/v1/invitropharmacology
      serviceId: invitropharmacology_core
    #############################
    #END invitro-pharmacology  section
    #############################

    #############################
    #START products section
    #############################
    products_core:
      path: ${api.base.path}/api/v1/products/**
      url: http://localhost:8084/api/v1/products
      serviceId: products_core
    products_core_alt:
      path: ${api.base.path}/api/v1/products(**)/**
      url: http://localhost:8084/api/v1/products
      serviceId: products_core
    #############################
    #END products section
    #############################

    #############################
    #START ssg4m section
    #############################
    ssg4m_core:
      path: ${api.base.path}/api/v1/ssg4m/**
      url: http://localhost:8088/ssg4m
      serviceId: ssg4m_core
    ssg4m_core_alt:
      path: ${api.base.path}/api/v1/ssg4m(**)/**
      url: http://localhost:8088/ssg4m
      serviceId: ssg4m_core_alt
    #############################
    #END ssg4m section
    #############################

    #############################
    #START substances/legacy section
    #############################
    api_legacy_ginas_app:
      path: /ginas/app/**
      url: http://localhost:8080
      stripPrefix: true
    api_legacy_gsrs_app:
      path: /gsrs/app/**
      url: http://localhost:8080
      stripPrefix: true
      
    #fallback anything else goes to substances
    legacy:
      path: /**
      url: http://localhost:8080
      serviceId: substances
    #############################
    #END substances/legacy section
    #############################

  ignored-patterns:
      - "/actuator/health"

ribbon:
  eureka:
    enabled: false

server.port: 8081
#management.endpoints.web.exposure.include: *
management.endpoints.web.exposure.include: 'routes,filters'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring.servlet.multipart.max-file-size:    100MB
spring.servlet.multipart.max-request-size: 100MB

eureka.client.enabled: false
#Adding high timeout so that GSRS won't time out waiting for response from server.

ix:
  authentication:
    allownonauthenticated: true
    #set the administrator email here to include their contact info in the error message
    #sysadmin-email: admin@example.com
    trustheader: true
    usernameheader: test-username

# Make sure microservices are given enoough time to perform tasks. 
zuul.host.socket-timeout-millis: 300000 

#Keeps + encoded characters encoded as +
zuul.forceOriginalQueryStringEncoding: true
