ALTER TABLE SRSCID_IMPURITIES_TEST ADD (tmp_TEST_DESCRIPTION  CLOB, tmp_COMMENTS  CLOB);
UPDATE SRSCID_IMPURITIES_TEST SET tmp_TEST_DESCRIPTION=TEST_DESCRIPTION, tmp_COMMENTS=COMMENTS;
COMMIT;
ALTER TABLE SRSCID_IMPURITIES_TEST DROP (TEST_DESCRIPTION, COMMENTS);
ALTER TABLE SRSCID_IMPURITIES_TEST RENAME COLUMN tmp_TEST_DESCRIPTION TO TEST_DESCRIPTION;
ALTER TABLE SRSCID_IMPURITIES_TEST RENAME COLUMN tmp_COMMENTS TO COMMENTS;