ALTER TABLE SRSCID_IMPURITIES_TEST 
ADD COLUMN tmp_TEST_DESCRIPTION LONGTEXT,
ADD COLUMN tmp_COMMENTS LONGTEXT;

UPDATE SRSCID_IMPURITIES_TEST 
SET tmp_TEST_DESCRIPTION = TEST_DESCRIPTION, tmp_COMMENTS = COMMENTS;
COMMIT;

ALTER TABLE SRSCID_IMPURITIES_TEST 
DROP COLUMN TEST_DESCRIPTION,
DROP COLUMN COMMENTS;

ALTER TABLE SRSCID_IMPURITIES_TEST 
RENAME COLUMN tmp_TEST_DESCRIPTION to TEST_DESCRIPTION,
RENAME COLUMN tmp_COMMENTS to COMMENTS;