create sequence ix_core_acl_seq start with 1 increment by  1;
create sequence ix_core_backup_seq start with 1 increment by  1;
create sequence ix_core_etag_seq start with 1 increment by  1;
create sequence ix_core_group_seq start with 1 increment by  1;
create sequence ix_core_namespace_seq start with 1 increment by  1;
create sequence ix_core_principal_seq start with 1 increment by  1;
create sequence ix_core_procjob_seq start with 1 increment by  1;
create sequence ix_core_procrec_seq start with 1 increment by  1;
create sequence ix_core_userprof_seq start with 1 increment by  1;
create sequence ix_core_value_seq start with 1 increment by  1;
create sequence ix_core_xref_seq start with 1 increment by  1;
create sequence ix_ginas_controlled_vocab_seq start with 1 increment by  1;
create sequence ix_ginas_vocabulary_term_seq start with 1 increment by  1;
create table ix_core_acl (id number(19,0) not null, perm number(10,0), primary key (id));
create table ix_core_acl_group (ix_core_acl_id number(19,0) not null, ix_core_group_id number(19,0) not null);
create table ix_core_acl_principal (ix_core_acl_id number(19,0) not null, ix_core_principal_id number(19,0) not null);
create table ix_core_backup (id number(19,0) not null, created timestamp, deprecated number(1,0) not null, modified timestamp, version number(19,0), compressed number(1,0) not null, data blob, kind varchar2(255 char), refid varchar2(255 char), sha1 varchar2(255 char), namespace_id number(19,0), primary key (id));
create table ix_core_edit (id varchar2(40 char) not null, batch varchar2(64 char), comments clob, created number(19,0), kind varchar2(255 char), new_value clob, old_value clob, path varchar2(1024 char), refid varchar2(255 char), version varchar2(255 char), editor_id number(19,0), primary key (id));
create table ix_core_etag (id number(19,0) not null, created timestamp, deprecated number(1,0) not null, modified timestamp, version number(19,0), count number(10,0), etag varchar2(16 char), filter varchar2(4000 char), method varchar2(10 char), path varchar2(255 char), query varchar2(2048 char), sha1 varchar2(40 char), skip number(10,0), status number(10,0), top number(10,0), total number(10,0), uri varchar2(4000 char), namespace_id number(19,0), primary key (id));
create table ix_core_figure (DTYPE varchar2(31 char) not null, id number(19,0) not null, caption varchar2(255 char), data blob, mime_type varchar2(255 char), sha1 varchar2(140 char), data_size number(10,0), url varchar2(1024 char), parent_id number(19,0), primary key (id));
create table ix_core_filedata (DTYPE varchar2(31 char) not null, id varchar2(40 char) not null, data blob, mime_type varchar2(255 char), sha1 varchar2(140 char), data_size number(19,0), primary key (id));
create table ix_core_group (id number(19,0) not null, name varchar2(255 char), primary key (id));
create table ix_core_group_principal (ix_core_group_id number(19,0) not null, ix_core_principal_id number(19,0) not null, primary key (ix_core_group_id, ix_core_principal_id));
create table ix_core_namespace (id number(19,0) not null, location varchar2(1024 char), modifier number(10,0), name varchar2(255 char), owner_id number(19,0), primary key (id));
create table ix_core_payload (id varchar2(40 char) not null, created timestamp, mime_type varchar2(128 char), name varchar2(1024 char), sha1 varchar2(40 char), capacity number(19,0), namespace_id number(19,0), primary key (id));
create table ix_core_payload_property (ix_core_payload_id varchar2(40 char) not null, ix_core_value_id number(19,0) not null);
create table ix_core_principal (DTYPE varchar2(31 char) not null, id number(19,0) not null, is_admin number(1,0), created timestamp, deprecated number(1,0) not null, email varchar2(255 char), modified timestamp, provider varchar2(255 char), uri varchar2(1024 char), username varchar2(255 char), version number(19,0), selfie_id number(19,0), primary key (id));
create table ix_core_procjob (id number(19,0) not null, last_update timestamp, message clob, job_start number(19,0), statistics clob, status number(10,0), job_stop number(19,0), version number(19,0), owner_id number(19,0), payload_id varchar2(40 char), primary key (id));
create table ix_core_procjob_key (ix_core_procjob_id number(19,0) not null, keys_id number(19,0) not null);
create table ix_core_procrec (id number(19,0) not null, last_update timestamp, message clob, name varchar2(128 char), rec_start number(19,0), status number(10,0), rec_stop number(19,0), job_id number(19,0), xref_id number(19,0), primary key (id));
create table ix_core_procrec_prop (ix_core_procrec_id number(19,0) not null, properties_id number(19,0) not null);
create table ix_core_session (id varchar2(40 char) not null, accessed number(19,0) not null, created number(19,0) not null, expired number(1,0) not null, location varchar2(255 char), profile_id number(19,0), primary key (id));
create table ix_core_structure (DTYPE varchar2(31 char) not null, id varchar2(40 char) not null, atropi number(10,0), charge number(10,0), count number(10,0), created timestamp, defined_stereo number(10,0), deprecated number(1,0) not null, digest varchar2(128 char), ez_centers number(10,0), formula varchar2(255 char), last_edited timestamp, molfile clob, mwt double precision, optical number(10,0), smiles clob, stereo_centers number(10,0), stereo varchar2(255 char), stereo_comments clob, version number(19,0), internal_references clob, record_access raw(255), created_by_id number(19,0), last_edited_by_id number(19,0), primary key (id));
create table ix_core_structure_link (ix_core_structure_id varchar2(40 char) not null, ix_core_xref_id number(19,0) not null);
create table ix_core_structure_property (ix_core_structure_id varchar2(40 char) not null, ix_core_value_id number(19,0) not null);
create table ix_core_userprof (id number(19,0) not null, created timestamp, deprecated number(1,0) not null, modified timestamp, version number(19,0), active number(1,0) not null, hashp varchar2(255 char), apikey varchar2(255 char), ROLES_JSON clob, salt varchar2(255 char), system_auth number(1,0) not null, namespace_id number(19,0), user_id number(19,0), primary key (id));
create table ix_core_userprof_prop (ix_core_userprof_id number(19,0) not null, ix_core_value_id number(19,0) not null);
create table ix_core_value (DTYPE varchar2(31 char) not null, id number(19,0) not null, label varchar2(255 char), href clob, term varchar2(255 char), heading varchar2(1024 char), major_topic number(1,0), text clob, data blob, mime_type varchar2(32 char), sha1 varchar2(40 char), data_size number(10,0), intval number(19,0), numval double precision, unit varchar2(255 char), average double precision, lval double precision, rval double precision, strval varchar2(1024 char), primary key (id));
create table ix_core_xref (id number(19,0) not null, created timestamp, deprecated number(1,0) not null, modified timestamp, version number(19,0), kind varchar2(255 char) not null, refid varchar2(40 char) not null, namespace_id number(19,0), primary key (id));
create table ix_core_xref_property (ix_core_xref_id number(19,0) not null, ix_core_value_id number(19,0) not null);
create table ix_ginas_agentmod (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, agent_modification_process varchar2(255 char), agent_modification_role varchar2(255 char), agent_modification_type varchar2(255 char), modification_group varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), agent_substance_uuid varchar2(40 char), amount_uuid varchar2(40 char), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_amount (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, approval_id varchar2(10 char), average double precision, high double precision, high_limit double precision, low double precision, low_limit double precision, non_numeric_value varchar2(255 char), type varchar2(255 char), units varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), primary key (uuid));
create table ix_ginas_code (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, code varchar2(255 char) not null, code_system varchar2(255 char), code_text clob, comments clob, type varchar2(255 char), url clob, created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_component (DTYPE varchar2(31 char) not null, uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, type varchar2(255 char), role varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), substance_uuid varchar2(40 char), amount_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_controlled_vocab (DTYPE varchar2(31 char) not null, id number(19,0) not null, created timestamp, deprecated number(1,0) not null, modified timestamp, version number(19,0), domain varchar2(255 char), editable number(1,0) not null, filterable number(1,0) not null, vocabulary_term_type varchar2(255 char), namespace_id number(19,0), primary key (id));
create table ix_ginas_definition (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, definition clob, created_by_id number(19,0), last_edited_by_id number(19,0), primary key (uuid));
create table ix_ginas_glycosylation (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, glycosylation_type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), c_glycosylation_sites_uuid varchar2(40 char), n_glycosylation_sites_uuid varchar2(40 char), o_glycosylation_sites_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_linkage (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, linkage varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), site_container_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_material (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, defining number(1,0), type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), amount_uuid varchar2(40 char), monomer_substance_uuid varchar2(40 char), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_mixture (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, created_by_id number(19,0), last_edited_by_id number(19,0), parent_substance_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_modifications (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, created_by_id number(19,0), last_edited_by_id number(19,0), primary key (uuid));
create table ix_ginas_moiety (inner_uuid varchar2(255 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, uuid varchar2(40 char), created_by_id number(19,0), last_edited_by_id number(19,0), count_uuid varchar2(40 char), owner_uuid varchar2(40 char), structure_id varchar2(40 char), primary key (inner_uuid));
create table ix_ginas_name (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, display_name number(1,0) not null, domains clob, full_name clob, languages clob, name varchar2(1024 char) not null, name_jurisdiction clob, preferred number(1,0) not null, std_name clob, type varchar2(32 char), created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_nameorg (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, deprecated_date timestamp, name_org varchar2(255 char) not null, created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_note (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, note clob, created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_nucleicacid (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, nucleic_acid_sub_type varchar2(255 char), nucleic_acid_type varchar2(255 char), sequence_origin varchar2(255 char), sequence_type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), modifications_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_nucleicacid_subunits (ix_ginas_nucleicacid_uuid varchar2(40 char) not null, ix_ginas_subunit_uuid varchar2(40 char) not null);
create table ix_ginas_otherlinks (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, linkage_type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), site_container_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_parameter (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, name varchar2(255 char) not null, type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), referenced_substance_uuid varchar2(40 char), value_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_physicalmod (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, modification_group varchar2(255 char), physical_modification_role varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_physicalpar (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, parameter_name varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), amount_uuid varchar2(40 char), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_polymer (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, created_by_id number(19,0), last_edited_by_id number(19,0), classification_uuid varchar2(40 char), display_structure_id varchar2(40 char), idealized_structure_id varchar2(40 char), primary key (uuid));
create table ix_ginas_property (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, defining number(1,0), name varchar2(255 char) not null, property_type varchar2(255 char), type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), referenced_substance_uuid varchar2(40 char), value_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_protein (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, disulf_json clob, protein_sub_type varchar2(255 char), protein_type varchar2(255 char), sequence_origin varchar2(255 char), sequence_type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), glycosylation_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_protein_subunit (ix_ginas_protein_uuid varchar2(40 char) not null, ix_ginas_subunit_uuid varchar2(40 char) not null);
create table ix_ginas_reference (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), citation clob, doc_type varchar2(255 char), document_date timestamp, id varchar2(255 char), public_domain number(1,0) not null, tags clob, uploaded_file varchar2(1024 char), url clob, created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_relationship (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, comments clob, interaction_type varchar2(255 char), originator_uuid varchar2(255 char), qualification varchar2(255 char), type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), amount_uuid varchar2(40 char), mediator_substance_uuid varchar2(40 char), owner_uuid varchar2(40 char), related_substance_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_site_lob (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, site_count number(19,0) not null, site_type varchar2(255 char), sites_json clob, sites_short_hand clob, created_by_id number(19,0), last_edited_by_id number(19,0), primary key (uuid));
create table ix_ginas_ssg1 (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, created_by_id number(19,0), last_edited_by_id number(19,0), primary key (uuid));
create table ix_ginas_strucdiv (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, developmental_stage varchar2(255 char), fraction_material_type varchar2(255 char), fraction_name varchar2(255 char), infra_specific_name varchar2(255 char), infra_specific_type varchar2(255 char), organism_author varchar2(255 char), organism_family varchar2(255 char), organism_genus varchar2(255 char), organism_species varchar2(255 char), part clob, part_location varchar2(255 char), source_material_class varchar2(255 char), source_material_state varchar2(255 char), source_material_type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), maternal_uuid varchar2(40 char), paternal_uuid varchar2(40 char), parent_substance_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_structuralmod (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, extent varchar2(255 char), location_type varchar2(255 char), modification_group varchar2(255 char), moleculare_fragment_role varchar2(255 char), residue_modified varchar2(255 char), structural_modification_type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), extent_amount_uuid varchar2(40 char), molecular_fragment_uuid varchar2(40 char), owner_uuid varchar2(40 char), site_container_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_substance (DTYPE varchar2(31 char) not null, uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), approval_id varchar2(20 char), approved timestamp, change_reason varchar2(255 char), definition_level number(10,0), definition_type number(10,0), status varchar2(255 char), class number(10,0), version varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), approved_by_id number(19,0), modifications_uuid varchar2(40 char), mixture_uuid varchar2(40 char), polymer_uuid varchar2(40 char), structurally_diverse_uuid varchar2(40 char), protein_uuid varchar2(40 char), nucleic_acid_uuid varchar2(40 char), specified_substance_uuid varchar2(40 char), structure_id varchar2(40 char), primary key (uuid));
create table ix_ginas_substance_mix_comp (ix_ginas_mixture_uuid varchar2(40 char) not null, ix_ginas_component_uuid varchar2(40 char) not null);
create table ix_ginas_substance_ss_comp (ix_ginas_ssg1_uuid varchar2(40 char) not null, ix_ginas_component_uuid varchar2(40 char) not null);
create table ix_ginas_substance_tags (ix_ginas_substance_uuid varchar2(40 char) not null, ix_core_value_id number(19,0) not null);
create table ix_ginas_substanceref (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, approval_ID varchar2(32 char), ref_pname varchar2(1024 char), refuuid varchar2(128 char), substance_class varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), primary key (uuid));
create table ix_ginas_subunit (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, sequence clob, subunit_index number(10,0), created_by_id number(19,0), last_edited_by_id number(19,0), primary key (uuid));
create table ix_ginas_sugar (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, sugar varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), owner_uuid varchar2(40 char), site_container_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_unit (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, attachmentMap clob, attachment_count number(10,0), label varchar2(255 char), structure clob, type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), amap_id number(19,0), amount_uuid varchar2(40 char), owner_uuid varchar2(40 char), primary key (uuid));
create table ix_ginas_vocabulary_term (DTYPE varchar2(31 char) not null, id number(19,0) not null, created timestamp, deprecated number(1,0) not null, modified timestamp, version number(19,0), description varchar2(4000 char), display varchar2(3000 char), filters clob, hidden number(1,0) not null, origin varchar2(255 char), regex varchar2(3000 char), selected number(1,0) not null, value varchar2(3000 char), system_category varchar2(255 char), fragment_structure varchar2(255 char), simplified_structure varchar2(255 char), namespace_id number(19,0), owner_id number(19,0), primary key (id));
create table polymer_classification (uuid varchar2(40 char) not null, created timestamp, current_version number(10,0) not null, deprecated number(1,0) not null, internal_version number(19,0), last_edited timestamp, record_access raw(255), internal_references clob, polymer_class varchar2(255 char), polymer_geometry varchar2(255 char), polymer_subclass clob, source_type varchar2(255 char), created_by_id number(19,0), last_edited_by_id number(19,0), parent_substance_uuid varchar2(40 char), primary key (uuid));
alter table ix_core_backup add constraint UK_6n0ebodjb5t7yoxowli7t5qud unique (refid);
create index refid_core_edit_index on ix_core_edit (refid);
create index kind_core_edit_index on ix_core_edit (kind);
alter table ix_core_etag add constraint UK_hvark3ftc0xax8dcbjuftcn7v unique (etag);
alter table ix_core_group add constraint UK_pm62da77mybok0t03dd0a9oum unique (name);
alter table ix_core_namespace add constraint UK_t3wv0p58vflh5n2vnj6rjan75 unique (name);
alter table ix_core_principal add constraint UK_p8p720bdp9bkws54yip7x1t47 unique (username);
create index property_structure_id_index on ix_core_structure_property (ix_core_structure_id);
create index property_value_id_index on ix_core_structure_property (ix_core_value_id);
create index value_label_index on ix_core_value (label);
create index value_term_index on ix_core_value (term);
create index xref_refid_index on ix_core_xref (refid);
create index xref_kind_index on ix_core_xref (kind);
create index ix_ix_ginas_code_code on ix_ginas_code (code);
create index ix_ix_ginas_code_code_system on ix_ginas_code (code_system);
create index ix_ix_ginas_code_type on ix_ginas_code (type);
create index ix_ix_ginas_code_owner on ix_ginas_code (owner_uuid);
alter table ix_ginas_controlled_vocab add constraint UK_ytqxax1bcj99cxs7tos6l26k unique (domain);
create index moiety_owner_index on ix_ginas_moiety (owner_uuid);
alter table ix_ginas_moiety add constraint UK_8cr4axbsithvjxcfhnltaejsp unique (uuid);
create index name_index on ix_ginas_name (name);
create index name_owner_index on ix_ginas_name (owner_uuid);
create index nameorg_owner_index on ix_ginas_nameorg (owner_uuid);
create index note_owner_index on ix_ginas_note (owner_uuid);
create index property_owner_index on ix_ginas_property (owner_uuid);
create index ref_id_index on ix_ginas_reference (id);
create index ref_owner_index on ix_ginas_reference (owner_uuid);
create index interaction_index on ix_ginas_relationship (interaction_type);
create index qualification_index on ix_ginas_relationship (qualification);
create index type_index on ix_ginas_relationship (type);
create index relate_originate_index on ix_ginas_relationship (originator_uuid);
create index rel_owner_index on ix_ginas_relationship (owner_uuid);
create index sub_approval_index on ix_ginas_substance (approval_id);
create index sub_dtype_index on ix_ginas_substance (DTYPE);
create index sub_ref_index on ix_ginas_substanceref (refuuid);
create index vocabulary_term_owner_index on ix_ginas_vocabulary_term (owner_id);
alter table ix_core_acl_group add constraint fkffablaywfq4inuntnok9otle foreign key (ix_core_group_id) references ix_core_group;
alter table ix_core_acl_group add constraint fk8a5l9ehfusnoigq1r4robs2da foreign key (ix_core_acl_id) references ix_core_acl;
alter table ix_core_acl_principal add constraint fkpf5d4mu9td8et6k5pgt78jma8 foreign key (ix_core_principal_id) references ix_core_principal;
alter table ix_core_acl_principal add constraint fkc9bo2bwjfcf7djff6coigl2b1 foreign key (ix_core_acl_id) references ix_core_acl;
alter table ix_core_backup add constraint fknulpohkjr0e7imml16hnmcl2c foreign key (namespace_id) references ix_core_namespace;
alter table ix_core_edit add constraint fkj2b3ncg8uek4q4tjua17gvkgi foreign key (editor_id) references ix_core_principal;
alter table ix_core_etag add constraint fk22kqxphqlg1d1hmsi2wtm6k0c foreign key (namespace_id) references ix_core_namespace;
alter table ix_core_figure add constraint fk911xrg14bag2m8e096i9d75lu foreign key (parent_id) references ix_core_figure;
alter table ix_core_group_principal add constraint fkp21u3ryjg094idoi9alrg90p7 foreign key (ix_core_principal_id) references ix_core_principal;
alter table ix_core_group_principal add constraint fk1voeekm54sy5sc3et2fqo0unx foreign key (ix_core_group_id) references ix_core_group;
alter table ix_core_namespace add constraint fkdgo5yjubgilh1nauv1t69gslx foreign key (owner_id) references ix_core_principal;
alter table ix_core_payload add constraint fkd150c5llpyncrqgpmqvvj8c9g foreign key (namespace_id) references ix_core_namespace;
alter table ix_core_payload_property add constraint fki6ubcj55u3pq0gm70ay7umle1 foreign key (ix_core_value_id) references ix_core_value;
alter table ix_core_payload_property add constraint fk6j2diflggrmws0k3suo8ms215 foreign key (ix_core_payload_id) references ix_core_payload;
alter table ix_core_principal add constraint fk6th1516rd9u5crfw7r12qtypk foreign key (selfie_id) references ix_core_figure;
alter table ix_core_procjob add constraint fkkx6oorfim5n6bhuy3j8wogyl5 foreign key (owner_id) references ix_core_principal;
alter table ix_core_procjob add constraint fkoxadf72bp8jsiuh1v42gx1t71 foreign key (payload_id) references ix_core_payload;
alter table ix_core_procjob_key add constraint fkr2mo13ikjb3bfw91uuwf7n5aw foreign key (keys_id) references ix_core_value;
alter table ix_core_procjob_key add constraint fk70h2uyrhvkuo84bwag5vljg9s foreign key (ix_core_procjob_id) references ix_core_procjob;
alter table ix_core_procrec add constraint fkpsv2ie5f4qjkar6kgis359efe foreign key (job_id) references ix_core_procjob;
alter table ix_core_procrec add constraint fkabpfcuyjcycb86bmc06xps4j6 foreign key (xref_id) references ix_core_xref;
alter table ix_core_procrec_prop add constraint fkjg8tmtxlf4d2vnb90e6i7exg0 foreign key (properties_id) references ix_core_value;
alter table ix_core_procrec_prop add constraint fktnw4u7w89a21880hmtva47pta foreign key (ix_core_procrec_id) references ix_core_procrec;
alter table ix_core_session add constraint fkfxn2t6y3dre527h1eymkt8lur foreign key (profile_id) references ix_core_userprof;
alter table ix_core_structure add constraint fksobht0ese9794r3q9k1q6i7gp foreign key (created_by_id) references ix_core_principal;
alter table ix_core_structure add constraint fk37rfonx9x7vmkwsru7dxxqhhk foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_core_structure_link add constraint fkdca3xgv2a5p344i74yc7sk89v foreign key (ix_core_xref_id) references ix_core_xref;
alter table ix_core_structure_link add constraint fk44si68uocnubt6vaobd4mgmmy foreign key (ix_core_structure_id) references ix_core_structure;
alter table ix_core_structure_property add constraint fk4n49941jj4uufoosy5n1g9rg6 foreign key (ix_core_value_id) references ix_core_value;
alter table ix_core_structure_property add constraint fkok4h9jsov59dh00wnrmsnd12x foreign key (ix_core_structure_id) references ix_core_structure;
alter table ix_core_userprof add constraint fks5bqupbwldu7843qnt8tuntnu foreign key (namespace_id) references ix_core_namespace;
alter table ix_core_userprof add constraint fknq0obnfqd9j3uh1uxdqn3ouq7 foreign key (user_id) references ix_core_principal;
alter table ix_core_userprof_prop add constraint fknfow9qqryxbxgppprcum5khf8 foreign key (ix_core_value_id) references ix_core_value;
alter table ix_core_userprof_prop add constraint fklloqe5wbjywhajh4tw6ilfnvg foreign key (ix_core_userprof_id) references ix_core_userprof;
alter table ix_core_xref add constraint fk6g9t8ugidjwe166t5nk7x2wqm foreign key (namespace_id) references ix_core_namespace;
alter table ix_core_xref_property add constraint fkaucrto6dcvyyq1n6jo332gqsf foreign key (ix_core_value_id) references ix_core_value;
alter table ix_core_xref_property add constraint fkmr6or6lteb684kq2e1dgsxl1w foreign key (ix_core_xref_id) references ix_core_xref;
alter table ix_ginas_agentmod add constraint fk837ol47m9wstcu74fp5toniam foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_agentmod add constraint fk2prhrnc5vlo55jxu1rxgpfdw1 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_agentmod add constraint fk2x5f4lw85tpkym1r3urwp2u3w foreign key (agent_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_agentmod add constraint fki7hwi4cyu1hi7yjo2ddwkig51 foreign key (amount_uuid) references ix_ginas_amount;
alter table ix_ginas_agentmod add constraint fk9ybw4linkblw3p4u25cq6qs0d foreign key (owner_uuid) references ix_ginas_modifications;
alter table ix_ginas_amount add constraint fkqsmrbuknll0fmv6jthf4cycy5 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_amount add constraint fk9leptgx7incy9twmrwcpeo2bm foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_code add constraint fkfwn6blkrhusg1xhrue0u820p foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_code add constraint fkpio633txjf8p5soyujcrtbx9v foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_code add constraint fke9p0ygr5drc93bxry80f9y215 foreign key (owner_uuid) references ix_ginas_substance;
alter table ix_ginas_component add constraint fkodvtp4qvwc7nyfr3lbc893o6m foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_component add constraint fkbbvqudmdnm60le1imuwb2uj5x foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_component add constraint fkql4nn094peyvxrwctj1ga2wp2 foreign key (substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_component add constraint fksqa51pxp5tbk6vyu34qbr8c5u foreign key (amount_uuid) references ix_ginas_amount;
alter table ix_ginas_controlled_vocab add constraint fk68jp62s2i2745esqr9px9s5a2 foreign key (namespace_id) references ix_core_namespace;
alter table ix_ginas_definition add constraint fk4kcslc98jcqx137enxl5fgs5t foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_definition add constraint fk9wxg9p9i1bi7qoxfcu9gkg9og foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_glycosylation add constraint fk6dapjdumuglm11xxawpupefqm foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_glycosylation add constraint fkpglm1avjx8n78aom78j3ju3bf foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_glycosylation add constraint fkqiim2s89ddjuxbkhpv3xa023j foreign key (c_glycosylation_sites_uuid) references ix_ginas_site_lob;
alter table ix_ginas_glycosylation add constraint fkffabrw84stgayaui9g1a4wk1g foreign key (n_glycosylation_sites_uuid) references ix_ginas_site_lob;
alter table ix_ginas_glycosylation add constraint fkmt1ufykgpny0dlxj36h6tgxwr foreign key (o_glycosylation_sites_uuid) references ix_ginas_site_lob;
alter table ix_ginas_linkage add constraint fkq619bp0y4e8y3c6efgyp2k8ux foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_linkage add constraint fkfctm6wmaejthxy8y5gtbaqd80 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_linkage add constraint fkotqo99g96i7epg4s384xushll foreign key (owner_uuid) references ix_ginas_nucleicacid;
alter table ix_ginas_linkage add constraint fkaao7lfx6xsyc4l1cpmsga4vre foreign key (site_container_uuid) references ix_ginas_site_lob;
alter table ix_ginas_material add constraint fk6ts531mold2ibya0c038hebea foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_material add constraint fkpab2df5aaru3riy5vxd86uve3 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_material add constraint fkipvr7dsgmt37oig421t41o385 foreign key (amount_uuid) references ix_ginas_amount;
alter table ix_ginas_material add constraint fkegxevel4526aib74sesmtu25e foreign key (monomer_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_material add constraint fkuvsb9isctq5ela0dqy2hhwti foreign key (owner_uuid) references ix_ginas_polymer;
alter table ix_ginas_mixture add constraint fk4tqay4hgaqpm3sq8rx9184jat foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_mixture add constraint fkjfwb6hqmtuoadhdx7wpkhxaju foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_mixture add constraint fko0yqo20vk9l8tqybgp75o23km foreign key (parent_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_modifications add constraint fknt72fojjxifrwa7bfwjw8cpm5 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_modifications add constraint fkpod9b4pm2tw1e4llfvayoivw4 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_moiety add constraint fkkw3ljg8rkiv07pcn0o0n3o02a foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_moiety add constraint fk3a5dgbi1pmatnvuta5a4wy3aq foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_moiety add constraint fkf0mktcfnu1ly1x7ubmf41lh2n foreign key (count_uuid) references ix_ginas_amount;
alter table ix_ginas_moiety add constraint fk8olyp6rpiq8yxtuk3mxsnbels foreign key (owner_uuid) references ix_ginas_substance;
alter table ix_ginas_moiety add constraint fkc3r993grtkv5al4opvpv554ga foreign key (structure_id) references ix_core_structure;
alter table ix_ginas_name add constraint fklhhdrsy7v2qr1amwmw0981mv2 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_name add constraint fkgwls3gldgeqmgliev3kcvhjml foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_name add constraint fkeqm42ow1b2o1c3uhu3d1k2efm foreign key (owner_uuid) references ix_ginas_substance;
alter table ix_ginas_nameorg add constraint fkk77bj1lax07ocd00s3sfmn6ot foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_nameorg add constraint fkm5w47bga21kw55x56q7jbbguj foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_nameorg add constraint fkqtmeq2vb6siyu40vxnw4c8vq foreign key (owner_uuid) references ix_ginas_name;
alter table ix_ginas_note add constraint fkge1aq2fv84ucy1ilwx97vpuwu foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_note add constraint fkpg2o4yxwwlbbw1rro1c5df60 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_note add constraint fkj3nrt8342rqojj5d4k24w5tgm foreign key (owner_uuid) references ix_ginas_substance;
alter table ix_ginas_nucleicacid add constraint fkm9yv3dunytjgyjfiq6r503lyr foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_nucleicacid add constraint fk6jk9rw9co4676wg98pvseggxc foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_nucleicacid add constraint fkck0ay4di4y12vsqd9gqw4qh4b foreign key (modifications_uuid) references ix_ginas_modifications;
alter table ix_ginas_nucleicacid_subunits add constraint fkjun57ycd07jv8oe3h8566r488 foreign key (ix_ginas_subunit_uuid) references ix_ginas_subunit;
alter table ix_ginas_nucleicacid_subunits add constraint fkdby8ustw4fo38x6e98cg814td foreign key (ix_ginas_nucleicacid_uuid) references ix_ginas_nucleicacid;
alter table ix_ginas_otherlinks add constraint fk9sukhdr4s0yje92m8hp82hitx foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_otherlinks add constraint fkigwh0j2irewbpsb1xgael3pim foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_otherlinks add constraint fkdub4td7p5ki0u4dl83j4u9ysr foreign key (owner_uuid) references ix_ginas_protein;
alter table ix_ginas_otherlinks add constraint fk5nj85bcu54jc56se3hm4q3chm foreign key (site_container_uuid) references ix_ginas_site_lob;
alter table ix_ginas_parameter add constraint fklbuqth4cgx61sh4rcci2mdl1o foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_parameter add constraint fklj93g1oplslasut6r924dft2l foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_parameter add constraint fk9ixg1ch1e0hueyta2dh4vlidg foreign key (owner_uuid) references ix_ginas_property;
alter table ix_ginas_parameter add constraint fkdxnyu34iqqponnw4bnj9hk8rb foreign key (referenced_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_parameter add constraint fkix1d880p7x7v51quhcre616af foreign key (value_uuid) references ix_ginas_amount;
alter table ix_ginas_physicalmod add constraint fk32ojpkiiy03fk8ro0eyclrbkh foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_physicalmod add constraint fk23yuiouuyqodtlxmjxopv0ybf foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_physicalmod add constraint fkd8fg9mm0ilkfdii08s5qsonde foreign key (owner_uuid) references ix_ginas_modifications;
alter table ix_ginas_physicalpar add constraint fkrfgl3mys5n5wiknd32enb7hmb foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_physicalpar add constraint fkd1w1xyqt12divo39phpoi2113 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_physicalpar add constraint fk4ce1vbnehe206ru4gctnlkidh foreign key (amount_uuid) references ix_ginas_amount;
alter table ix_ginas_physicalpar add constraint fk1e30fjxi7rv1m875713tges77 foreign key (owner_uuid) references ix_ginas_physicalmod;
alter table ix_ginas_polymer add constraint fk8axkm0cbpwpc43krkhw8y6tad foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_polymer add constraint fk5o81f597yvub0mf1b6cnqx8ev foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_polymer add constraint fktn8tft3hwqnpv8tkfhtbh5jsm foreign key (classification_uuid) references polymer_classification;
alter table ix_ginas_polymer add constraint fkcd56mdyyo9bvrrd80w0y8iixl foreign key (display_structure_id) references ix_core_structure;
alter table ix_ginas_polymer add constraint fk264hsvr9c8q3w1e51j99ua2d0 foreign key (idealized_structure_id) references ix_core_structure;
alter table ix_ginas_property add constraint fktla10hxba7smca0g675soamsq foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_property add constraint fkafltirwo87s1so6vigtf1s8mn foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_property add constraint fkrlu3e72lq9y59122xd75q51vt foreign key (owner_uuid) references ix_ginas_substance;
alter table ix_ginas_property add constraint fkoh8nhvrowpdthcxj69pwkke9t foreign key (referenced_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_property add constraint fkpbekqdofak8ol2fq92f5onn1t foreign key (value_uuid) references ix_ginas_amount;
alter table ix_ginas_protein add constraint fk6ay15bqty5r2xmk13a4ld75rm foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_protein add constraint fkpovxe3t3ycsa1x6xivr20ukbh foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_protein add constraint fkec7ms0paeosyymbpsnbu5pjfb foreign key (glycosylation_uuid) references ix_ginas_glycosylation;
alter table ix_ginas_protein_subunit add constraint fklk7qxuwt9o7g8k6rphr5jj7ey foreign key (ix_ginas_subunit_uuid) references ix_ginas_subunit;
alter table ix_ginas_protein_subunit add constraint fk39xyg6fxghld06apb91xc1xt6 foreign key (ix_ginas_protein_uuid) references ix_ginas_protein;
alter table ix_ginas_reference add constraint fkpv1epn9el8d1fpqct4px1nio7 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_reference add constraint fk975dqn3b674b23ga0igmmct25 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_reference add constraint fkk7kui3q4qm7pwdq679ibkyi5h foreign key (owner_uuid) references ix_ginas_substance;
alter table ix_ginas_relationship add constraint fk70gmjxu8uevujxd4uetj6nfm3 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_relationship add constraint fkmsd9lm6ayae7qbwp1iv50ftbb foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_relationship add constraint fk492eul84p3uecmkpqmd8ujvkb foreign key (amount_uuid) references ix_ginas_amount;
alter table ix_ginas_relationship add constraint fksim8mqlrevhpl0aa0hrdh3wwe foreign key (mediator_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_relationship add constraint fkr1msd0rheudj2srgokqrftrek foreign key (owner_uuid) references ix_ginas_substance;
alter table ix_ginas_relationship add constraint fkb6yhrsc7dprxg0apyknpue5ij foreign key (related_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_site_lob add constraint fkfbc7le8ehsxj39t2yikmmy3py foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_site_lob add constraint fkh2cg1v3f9ha8t0w4l8iprib2g foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_ssg1 add constraint fk3tljtp4q2e94j2q27hgnnhse4 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_ssg1 add constraint fkle7gsf4fuf75tsrvksgvkjc25 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_strucdiv add constraint fkqpk4af5q91r4nsm521kd57298 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_strucdiv add constraint fk4epq4o38ci57y71dxu7ootl41 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_strucdiv add constraint fkhh72pwq35aaqgv370uavhtnjh foreign key (maternal_uuid) references ix_ginas_substanceref;
alter table ix_ginas_strucdiv add constraint fk6lcu1945kbaxi6fmir3qt5ugk foreign key (paternal_uuid) references ix_ginas_substanceref;
alter table ix_ginas_strucdiv add constraint fk27p7qapsxr5d2efscf8k7521 foreign key (parent_substance_uuid) references ix_ginas_substanceref;
alter table ix_ginas_structuralmod add constraint fkndd0pxjud610e953hg730emw foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_structuralmod add constraint fk1ysjs1dx6uo8flj8rkiscscx4 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_structuralmod add constraint fktkmtm9vpmaklmypp3jad1pspp foreign key (extent_amount_uuid) references ix_ginas_amount;
alter table ix_ginas_structuralmod add constraint fk6n3mtotuwqi717fr2evp3dfxi foreign key (molecular_fragment_uuid) references ix_ginas_substanceref;
alter table ix_ginas_structuralmod add constraint fkoi4vt2lg0x2v3s4urckwjb3s3 foreign key (owner_uuid) references ix_ginas_modifications;
alter table ix_ginas_structuralmod add constraint fkb94sjca6cclvcwtx2osvdeuu foreign key (site_container_uuid) references ix_ginas_site_lob;
alter table ix_ginas_substance add constraint fka9b6lpf9y3l0t04rviskjs8o1 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_substance add constraint fk9hlo5n1alfg4rgloypq8agc3e foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_substance add constraint fkmb0vxvmui506xtkh18lw1ucym foreign key (approved_by_id) references ix_core_principal;
alter table ix_ginas_substance add constraint fk30b2jg1r8dr4ibvt3f4h7ui3b foreign key (modifications_uuid) references ix_ginas_modifications;
alter table ix_ginas_substance add constraint fkekk08a5uheng9eocf61xo4m2l foreign key (mixture_uuid) references ix_ginas_mixture;
alter table ix_ginas_substance add constraint fkncdqbv3ilcg21bws3e3y0xwg4 foreign key (polymer_uuid) references ix_ginas_polymer;
alter table ix_ginas_substance add constraint fkhrs798kf99tmayeg8hjbo9vdl foreign key (structurally_diverse_uuid) references ix_ginas_strucdiv;
alter table ix_ginas_substance add constraint fkcw3qqer4es16onh3qgcuf6jb8 foreign key (protein_uuid) references ix_ginas_protein;
alter table ix_ginas_substance add constraint fk8lglxcodtpv6nj0wbw61cpdk9 foreign key (nucleic_acid_uuid) references ix_ginas_nucleicacid;
alter table ix_ginas_substance add constraint fkd29meikxu3elfx1w5dket3ia5 foreign key (specified_substance_uuid) references ix_ginas_ssg1;
alter table ix_ginas_substance add constraint fkau9cajhw1nffg9w1vh0am4ls4 foreign key (structure_id) references ix_core_structure;
alter table ix_ginas_substance_mix_comp add constraint fkjsfcmh12rru7tls24cbkbmb0t foreign key (ix_ginas_component_uuid) references ix_ginas_component;
alter table ix_ginas_substance_mix_comp add constraint fkpubptahgdm25hadwlf3pwlfap foreign key (ix_ginas_mixture_uuid) references ix_ginas_mixture;
alter table ix_ginas_substance_ss_comp add constraint fkb8ofx08elpr455o7a72rrr9tm foreign key (ix_ginas_component_uuid) references ix_ginas_component;
alter table ix_ginas_substance_ss_comp add constraint fkaf57kow6qnxnp2ya35n21jiyo foreign key (ix_ginas_ssg1_uuid) references ix_ginas_ssg1;
alter table ix_ginas_substance_tags add constraint fkjlsvy9nlwl3vf5mvhcvf0y80k foreign key (ix_core_value_id) references ix_core_value;
alter table ix_ginas_substance_tags add constraint fk2hyjvdeqia2qiemoagh6yjq6b foreign key (ix_ginas_substance_uuid) references ix_ginas_substance;
alter table ix_ginas_substanceref add constraint fko2bjxrp2qi847appx7ecf65vc foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_substanceref add constraint fkm6qbi1moehd7wqh9w2ip412us foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_subunit add constraint fk7kjfdjus3twoyg4vd2jp367n6 foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_subunit add constraint fk9pyegqu1n4ekd45fdmitw12t7 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_sugar add constraint fke6ndxx94bjimsgux4lygsh51f foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_sugar add constraint fk1p4pfd811kxxjqfxbiuu9sknv foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_sugar add constraint fkkx0aeyak8r0byugf719kqu7ms foreign key (owner_uuid) references ix_ginas_nucleicacid;
alter table ix_ginas_sugar add constraint fkpx5dhn0168ipbpu04xgmby97y foreign key (site_container_uuid) references ix_ginas_site_lob;
alter table ix_ginas_unit add constraint fkl4qe419byvtxe3epgd4a50glc foreign key (created_by_id) references ix_core_principal;
alter table ix_ginas_unit add constraint fknbsd63mfulnly1dtk7f6vxcq4 foreign key (last_edited_by_id) references ix_core_principal;
alter table ix_ginas_unit add constraint fkq8b5gi5r7thxi8vyrli5lrtu2 foreign key (amap_id) references ix_core_value;
alter table ix_ginas_unit add constraint fk2x4h6n93ud35rtm5nxt7xrcmw foreign key (amount_uuid) references ix_ginas_amount;
alter table ix_ginas_unit add constraint fkf3rxpagehygabef32q3kn4am foreign key (owner_uuid) references ix_ginas_polymer;
alter table ix_ginas_vocabulary_term add constraint fk3t5cvdqdtqn0eqc1654fbxhqt foreign key (namespace_id) references ix_core_namespace;
alter table ix_ginas_vocabulary_term add constraint fkbk04rq7l3tav8pey5rm2j14hm foreign key (owner_id) references ix_ginas_controlled_vocab;
alter table polymer_classification add constraint fk9tp2yhc5vdofsdnx5cit45hdy foreign key (created_by_id) references ix_core_principal;
alter table polymer_classification add constraint fk6bup6ku2dri7cl4rgno4fd6dd foreign key (last_edited_by_id) references ix_core_principal;
alter table polymer_classification add constraint fkl3chbblh2guqlw9ikn9grc3vb foreign key (parent_substance_uuid) references ix_ginas_substanceref;
